# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TafCF5e3Jzcxi4-WYSNMJpyOjiG0PifD
"""

import streamlit as st

# ランレングス圧縮を行う関数
def run_length_encoding(input_str):
    encoded_str = ''
    count = 1
    encoded_data = []

    if len(input_str) == 0:
        return encoded_str, encoded_data

    for i in range(1, len(input_str)):
        if input_str[i] == input_str[i - 1]:
            count += 1
        else:
            encoded_str += input_str[i - 1] + str(count)
            encoded_data.append((input_str[i - 1], count))
            count = 1

    encoded_str += input_str[-1] + str(count)
    encoded_data.append((input_str[-1], count))

    return encoded_str, encoded_data

# 圧縮率を求める関数
def calculate_compression_rate(input_str, encoded_str):
    original_size = len(input_str)
    compressed_size = len(encoded_str)
    compression_rate = (1 - compressed_size / original_size) * 100
    return original_size, compressed_size, compression_rate

# Streamlit アプリケーションの UI
st.title('📦 ランレングス圧縮ツール')

# 入力
input_str = st.text_input('✏️ 半角アルファベットを入力してください:')

if input_str:
    # 圧縮処理
    encoded_str, encoded_data = run_length_encoding(input_str)
    original_size, compressed_size, compression_rate = calculate_compression_rate(input_str, encoded_str)

    # 元のデータ
    st.header('🗃️ 元のデータ')
    st.info(f'入力データ: **{input_str}**')
    st.write(f'元のデータのサイズ: **{original_size} バイト**')

    # 圧縮後のデータ
    st.header('🔧 圧縮後のデータ')
    st.success(f'ランレングス圧縮後のデータ: **{encoded_str}**')
    st.write(f'圧縮後のデータのサイズ: **{compressed_size} バイト**')

    # 圧縮率
    st.header('📉 圧縮率の結果')
    st.latex(r'''
    圧縮率 = \frac{{\text{{元のサイズ}} - \text{{圧縮後のサイズ}}}}{{\text{{元のサイズ}}}} \times 100
    ''')
    st.latex(rf'''
    圧縮率 = \frac{{{original_size} - {compressed_size}}}{{{original_size}}} \times 100 = {compression_rate:.2f}\%
    ''')
    st.warning(f'圧縮率: **{compression_rate:.2f}%**')

    # 圧縮後のデータ詳細
    st.header('🔍 圧縮後のデータ詳細')
    st.table([{'文字': char, '出現回数': count} for char, count in encoded_data])

    # 注意事項
    st.caption('※ 半角アルファベット以外の入力は無視されます。')